// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: inventories/product_category_service.proto

package inventories

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProductCategoryService_Create_FullMethodName = "/wiradata.inventories.ProductCategoryService/Create"
	ProductCategoryService_Update_FullMethodName = "/wiradata.inventories.ProductCategoryService/Update"
	ProductCategoryService_View_FullMethodName   = "/wiradata.inventories.ProductCategoryService/View"
	ProductCategoryService_Delete_FullMethodName = "/wiradata.inventories.ProductCategoryService/Delete"
	ProductCategoryService_List_FullMethodName   = "/wiradata.inventories.ProductCategoryService/List"
)

// ProductCategoryServiceClient is the client API for ProductCategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductCategoryServiceClient interface {
	Create(ctx context.Context, in *ProductCategory, opts ...grpc.CallOption) (*ProductCategory, error)
	Update(ctx context.Context, in *ProductCategory, opts ...grpc.CallOption) (*ProductCategory, error)
	View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ProductCategory, error)
	Delete(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MyBoolean, error)
	List(ctx context.Context, in *ListProductCategoryRequest, opts ...grpc.CallOption) (ProductCategoryService_ListClient, error)
}

type productCategoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductCategoryServiceClient(cc grpc.ClientConnInterface) ProductCategoryServiceClient {
	return &productCategoryServiceClient{cc}
}

func (c *productCategoryServiceClient) Create(ctx context.Context, in *ProductCategory, opts ...grpc.CallOption) (*ProductCategory, error) {
	out := new(ProductCategory)
	err := c.cc.Invoke(ctx, ProductCategoryService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCategoryServiceClient) Update(ctx context.Context, in *ProductCategory, opts ...grpc.CallOption) (*ProductCategory, error) {
	out := new(ProductCategory)
	err := c.cc.Invoke(ctx, ProductCategoryService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCategoryServiceClient) View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ProductCategory, error) {
	out := new(ProductCategory)
	err := c.cc.Invoke(ctx, ProductCategoryService_View_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCategoryServiceClient) Delete(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MyBoolean, error) {
	out := new(MyBoolean)
	err := c.cc.Invoke(ctx, ProductCategoryService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCategoryServiceClient) List(ctx context.Context, in *ListProductCategoryRequest, opts ...grpc.CallOption) (ProductCategoryService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProductCategoryService_ServiceDesc.Streams[0], ProductCategoryService_List_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &productCategoryServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProductCategoryService_ListClient interface {
	Recv() (*ListProductCategoryResponse, error)
	grpc.ClientStream
}

type productCategoryServiceListClient struct {
	grpc.ClientStream
}

func (x *productCategoryServiceListClient) Recv() (*ListProductCategoryResponse, error) {
	m := new(ListProductCategoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductCategoryServiceServer is the server API for ProductCategoryService service.
// All implementations must embed UnimplementedProductCategoryServiceServer
// for forward compatibility
type ProductCategoryServiceServer interface {
	Create(context.Context, *ProductCategory) (*ProductCategory, error)
	Update(context.Context, *ProductCategory) (*ProductCategory, error)
	View(context.Context, *Id) (*ProductCategory, error)
	Delete(context.Context, *Id) (*MyBoolean, error)
	List(*ListProductCategoryRequest, ProductCategoryService_ListServer) error
	mustEmbedUnimplementedProductCategoryServiceServer()
}

// UnimplementedProductCategoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductCategoryServiceServer struct {
}

func (UnimplementedProductCategoryServiceServer) Create(context.Context, *ProductCategory) (*ProductCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProductCategoryServiceServer) Update(context.Context, *ProductCategory) (*ProductCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProductCategoryServiceServer) View(context.Context, *Id) (*ProductCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedProductCategoryServiceServer) Delete(context.Context, *Id) (*MyBoolean, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProductCategoryServiceServer) List(*ListProductCategoryRequest, ProductCategoryService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProductCategoryServiceServer) mustEmbedUnimplementedProductCategoryServiceServer() {
}

// UnsafeProductCategoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductCategoryServiceServer will
// result in compilation errors.
type UnsafeProductCategoryServiceServer interface {
	mustEmbedUnimplementedProductCategoryServiceServer()
}

func RegisterProductCategoryServiceServer(s grpc.ServiceRegistrar, srv ProductCategoryServiceServer) {
	s.RegisterService(&ProductCategoryService_ServiceDesc, srv)
}

func _ProductCategoryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCategoryService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryServiceServer).Create(ctx, req.(*ProductCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCategoryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCategoryService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryServiceServer).Update(ctx, req.(*ProductCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCategoryService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCategoryService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryServiceServer).View(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCategoryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCategoryService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryServiceServer).Delete(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCategoryService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListProductCategoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductCategoryServiceServer).List(m, &productCategoryServiceListServer{stream})
}

type ProductCategoryService_ListServer interface {
	Send(*ListProductCategoryResponse) error
	grpc.ServerStream
}

type productCategoryServiceListServer struct {
	grpc.ServerStream
}

func (x *productCategoryServiceListServer) Send(m *ListProductCategoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ProductCategoryService_ServiceDesc is the grpc.ServiceDesc for ProductCategoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductCategoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wiradata.inventories.ProductCategoryService",
	HandlerType: (*ProductCategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductCategoryService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProductCategoryService_Update_Handler,
		},
		{
			MethodName: "View",
			Handler:    _ProductCategoryService_View_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProductCategoryService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _ProductCategoryService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inventories/product_category_service.proto",
}
